import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';

const execAsync = promisify(exec);

async function runQALoop() {
  console.log('🤖 Starting RogueReader QA Loop...\n');

  try {
    console.log('Running Puppeteer E2E tests...');
    await execAsync('npm run test:e2e');
    console.log('✅ All tests passed!\n');
    console.log('✨ No bugs detected. Game loop is healthy.\n');
    return;
  } catch (error) {
    console.log('❌ Tests failed. Generating bug report...\n');
  }

  try {
    const report = JSON.parse(
      await fs.readFile('tests/reports/latest-failure.json', 'utf-8')
    );

    const agentPrompt = `# QA Test Failure Report

## Bug Detected
**${report.bug}**

**Severity**: ${report.severity}
**Timestamp**: ${report.timestamp}

## Evidence
- Screenshot: ${report.screenshotPath}
${report.rooms ? `- Rooms found: ${report.rooms.length}` : ''}
${report.distance !== undefined ? `- Player-to-boss distance: ${report.distance} tiles` : ''}
${report.exploitFound ? `- **Exploit**: ${report.exploitFound}` : ''}

## Design Requirement Violated
${report.designRequirement}

## Suggested Fix
${report.suggestedFix.map((fix: string, i: number) => `${i + 1}. ${fix}`).join('\n')}

## Debug Data
\`\`\`json
${JSON.stringify(report, null, 2)}
\`\`\`

---

## Next Steps
1. Review the screenshot at: ${report.screenshotPath}
2. Examine the code sections mentioned in "Suggested Fix"
3. Implement the fix
4. Re-run \`npm run qa-loop\` to verify

**Automation Note**: This report was generated by the Puppeteer QA system to catch design violations and gameplay bugs early. See DESIGN.md "Automated Testing Strategy" for details.
`;

    await fs.writeFile('tests/reports/agent-prompt.md', agentPrompt);

    console.log('📝 Bug report generated: tests/reports/agent-prompt.md');
    console.log('📸 Screenshot saved: ' + report.screenshotPath);
    console.log('\n🔍 Review the report and fix the issues, then re-run this script.\n');

  } catch (error) {
    console.log('⚠️  No failure report found. Check test output above for details.\n');
    console.error(error);
  }
}

runQALoop().catch(console.error);
